version: "3.9"

services:
  env_ubuntu:
    build:
      context: .
      args:
        - gh_token=<GitHubToken>
        - gh_email=<GitHubUserEmail>
        - gh_uname=<GitHubUserName>
        - gh_repo_owner=RicoKursidem
        - gh_repo_name=dhbw-deep-groove-with-pytorch
        - gh_branch=AutoML
    
    tty: true
    image: ubuntu_python_env
    container_name: ubuntu_python_env